#!/bin/bash
#
# Extract battery health in percent for conky.
#
# Copyright (C) 2022  David Hobach  GPLv3
# version: 0.3
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.
# 

function no_bat {
  echo "-"
  exit 0
}

charge_full="$(cat /sys/class/power_supply/BAT*/charge_full)" || no_bat
[ -n "$charge_full" ] || no_bat
charge_full_design="$(cat /sys/class/power_supply/BAT*/charge_full_design)" || no_bat
[ -n "$charge_full_design" ] || no_bat
echo "$(( 100 * $charge_full / $charge_full_design ))%"
