#!/bin/bash
#
# qubes-conky startup script
#
# Copyright (C) 2020  David Hobach  GPLv3
# version: 2.0
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.
# 

#name & directory of this script (hopefully...)
SCRIPT_DIR="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
#SCRIPT_NAME="$(basename "$0")"

#parseConf [input file] [output file]
function parseConf {
local in="$1"
local out="$2"

local line=""
local re='^--INCLUDE_CONKY "(.*)"$'
while IFS= read -r line || [ -n "$line" ] ; do
	if [[ "$line" =~ $re ]] ; then
		local file="${BASH_REMATCH[1]}"
		[ -f "$file" ] && parseConf "$file" "$out"
	else
		echo "$line" >> "$out"
	fi
done < "$in"
}

#startConkyInstance [conky config file]
function startConkyInstance {
local conf="$SCRIPT_DIR/$1"
local finalConf=
finalConf="$(mktemp)" || exit 1
echo "$1: $finalConf"
parseConf "$conf" "$finalConf"

conky -c "$finalConf"
}

cd "$SCRIPT_DIR" || exit 1
killall conky
#unfortunately conky doesn't support multiple conky columns easily so we simply start multiple conky instances
startConkyInstance "conky_perf.conf"
startConkyInstance "conky_qubes.conf"
startConkyInstance "conky_qubesSettings.conf"
