#!/bin/bash
#
# List recently blocked dom0 USB devices for conky.
#
# If you use `usbguard, this can be used as such in your custom conky
# config:
# ```
# ${execpi 60 sudo ./usbguard_conky "/var/log/usbguard.log" 12}
# ```
#
# Copyright (C) 2021  David Hobach  GPLv3
# version: 0.8
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.
# 

function error {
  echo '${color red}ERROR: '"$1"'${color}'
  exit 1
}

function usage {
  error "Usage: usbguard_conky [usbguard log file] [hours to look back]"
}

[ $EUID -eq 0 ] || error "This script must be run as root."
log="$1"
[ -n "$log" ] || usage
hours="$2"
[ -n "$hours" ] || usage

input="$(set -o pipefail ; grep -E '^.*type=Policy.Device.Update+.*target.new=(block|reject)' "$log" | tail -n10)" || error "Failed to get the input."
now="$(date +%s)" || error "Failed to obtain the current time."

re='^\[([0-9]+).* device='"'"'.* id ([^ ]+) serial .* name "([^"]*)".*$'
cnt=0
while IFS= read -r line ; do
  #parse
  [[ "$line" =~ $re ]] || error "Not matching: $line"$'\n'"This is unexpected. Format change?"
  ts="${BASH_REMATCH[1]}"
  id="${BASH_REMATCH[2]}"
  name="${BASH_REMATCH[3]}"

  diff=$(( ( $now - $ts ) / 3600 ))
  if [ $diff -lt $hours ] ; then
    cnt=$(( cnt + 1 ))
    ts_readable="$(date "--date=@$ts" +'%F %H:%M:%S')" || error "Failed to convert $ts to a readable format."
    echo '${color red}'"$ts_readable $name ($id)"'${color}'
  fi
done <<< "$input"

if [ $cnt -eq 0 ] ; then
    echo '${color green}None${color}'
fi
exit 0
